#!/usr/bin/env sh

if [ "`git status -s`" != "" ]; then
  echo "Cannot deploy! You have changes not committed"
  exit -1
fi

if [ "$1" = "production" ]
then
    REVISION=production

    echo "Promoting deploy to \033[1;41m $REVISION \033[0m..."

    heroku pipelines:promote --remote staging
else
    REVISION=staging

    echo
    echo ' *** Running tests...'
    mix test

    if [ $? != 0 ]
    then
        echo
        echo ' *** Test status: FAILED'
        echo ' *** Exiting... Please fix the tests then release the module again.'
        exit -1
    else
        echo
        echo ' *** Test status: SUCCESS'
    fi

    echo "Starting deploy on \033[1;41m $REVISION \033[0m..."

    git checkout master && git pull && git push
    if [ $? != 0 ]; then
        echo "ABORT deploy! There are merge conflicts."
        exit -1
    fi
fi

echo
echo ' *** Notify deploy... TODO'
# rake bugsnag:deploy BUGSNAG_REVISION=$REVISION BUGSNAG_RELEASE_STAGE=$REVISION

